export const GET_ALL_RECIPES = "GET_ALL_RECIPES"
export const GET_RECIPE = 'GET_RECIPE'
export const FILTER_BY_TITLE = 'FILTER_BY_TITLE'
export const FILTER_BY_PUNTUATION = 'FILTER_BY_PUNTUATION'
export const GET_SEARCH_RECIPE = 'GET_SEARCH_RECIPE'